### ISSUE TITLE
Disbursements and expenditures

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2024-Index-indicator-definitions#13]
## Description

Individual actual financial disbursements and expenditures must be related to individual activities and must be on a per-transaction basis.

This is only expected if the activity is in the implementation, completion or post-completion phase.

## Current test

```python
   Given an IATI activity 
   And the activity is current 
   And `activity-status/@code` is one of 2, 3 or 4 
   Then `transaction[transaction-type/@code="3" or transaction-type/@code="4" should be present
```

**Comment by kossoverpn** [comment]
MCC has concerns with this change as it penalizes a model with larger programs that are broken out into smaller activities for reporting. Our programs are composed of activities that have an ebb and flow of work and funds over their five-year lifecycle. Due to this, there are activities which are part of an active program but have not had any transactions in the past 12-months and will have transactions in the future. These are still active activities.

Additionally, we would like to clarify whether a ‘0’ value transaction would pass the test.

**Comment by YohannaLoucheur** [comment]
The logic of the proposed change is not clear at all. On what basis do we expect an activity to have a transaction in the last 12 months? There could be several reasons for activities not to have recent transactions.
The logic is even less clear if projects in Completion and Post-Completion stage are included. Why would we expect them to have recent transactions?

**Comment by hsd25** [comment]
I fully agree, we need more guidance and explanations on that one. Some projects could be "active" but with no disbursements yet. The reasons for why no disbursement have been made within 12 months are quite big. On the 12 months, what date are you looking for ? approval date? signature date? and depending on donors type 1 and 2 dates have different meaning...

**Comment by jucobins** [comment]
On the EBRD side, the logic is not entirely clear to us. We cannot expect all of our committed projects to have disbursement activity within the past 12-month period. This is especially true for most of our infrastructure projects with conditions precedent. Linking negatively a transparency score to the absence of activity seems counterintuitive.

**Comment by HermanvanLoon** [comment]
This metric also ignores commitments. It is very well possible that a new activity in the implementation phase has a commitment (e.g. signed contract with a certain value) but no funds have been disbursed or extended yet. Wouldn't the proposed metric penalize the timely publication of such new projects?

**Comment by stevieflow** [comment]
I agree with all other responses

Additionally, for some organisations there could also be a legitimate state whereby an activity could have completed disbursements, but may still be "current" (according to #1) and only have loan-repayment transactions (in the last 12 months).  This proposed change would render the activity as a fail.

Also - as posted in #12 

> Furthermore, my understanding of the ATI methodology is that the "current activity" is a separate, and cross-cutting, "test", as defined in https://github.com/pwyf/2024-Index-indicator-definitions/issues/1. By bringing in an additional attempt to further refine "current activity" here, there's a real risk of undermining and contradicting the wider methodology.

**Comment by abdulriza** [comment]
I also agree with all the comments above. Since the test doesn't seem to have any relevance to the activity dates and includes closed projects in the activity status, it doesn't make sense to expect expenses in the current year if the reported activity was closed last year. Also, there can be various valid reasons for an ongoing project to not to have expenses in the current year.

**Comment by publishwhatyoufund** [comment]
Thanks for your comments, we have considered these carefully and agree that many business models could results in no disbursements. We will not be taking this proposal forward. 


In addition, currently a ‘0’ value is accepted for disbursements or expenditure.
