### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by publishwhatyoufund** [pwyf/2024-Index-indicator-definitions#23]
## Description
The terms and conditions of the activity may also be referred to as benchmarks, priors, deliverables or involve words such as “subject to…”. They are specific to an individual activity and explain what the recipient must do in order to be eligible for the funds to be released.
Any policy conditions related to an activity must be published here. 

This is only expected if the activity is in the implementation, completion or post-completion phase.

## Current test
Firstly:
```python
For each current activity,
if `activity-status/@code` is one of (2, 3, 4)
And `default-aid-type/@code` is not any of B01, B02, B03, B04, D01, D02, E01, E02, F01, H01, H02, H03, H04, H05 or G01
    And `transaction/aid-type/@code` is not any of B01, B02, B03, B04, D01, D02, E01, E02, F01, H01, H02, H03, H04, H05 or G01
then `conditions` should be present

```
Secondly:
```python
if `activity-status/@code` is one of (2, 3, 4)
And `default-aid-type/@code` is not any of B01, B02, B03, B04, D01, D02, E01, E02, F01, H01, H02, H03, H04, H05 or G01
    And `transaction/aid-type/@code` is not any of B01, B02, B03, B04, D01, D02, E01, E02, F01, H01, H02, H03, H04, H05 or G01
then `document-link/category[@code="A04"]` should be present

```

**Comment by YohannaLoucheur** [comment]
Some donors have general eligibility conditions rather than conditions specific to each project. Publishing these on their website rather than repeating them for every activity in the IATI file (which would not be a useful nor effective thing to do) should be accepted as an alternative approach.

**Comment by hsd25** [comment]
I agree @YohannaLoucheur

**Comment by stevieflow** [comment]
@YohannaLoucheur if the general conditions are published on the donor website, could that be a simple ``document-link`` (type A04, format=text/html") within the activity?

I think it important to remember that an IATI activity can get used in a variety of places, rather than _just_ the XML file it is published in.  Hence, even if it can see to be repetitive and superfluous to carry the same info (such as condition text/document-link) in each and every activity, somebody using the data may not have access to this assumption, when viewing the activity in isolation

---------
@YohannaLoucheur alternatively (and more in support of your point) - a publisher could link to general conditions in their organisation file.  But - I'm not clear if code B15 from the ``document-link`` [category codelist](https://iatistandard.org/en/iati-standard/203/codelists/documentcategory/) would be 100% applicable here (there's no other context to what "General Terms and Conditions" means...)

[codes A apply to activity documents; B to the organsation file, in that codelist)

If that case were supported, this test would need to be adjusted to include coverage of such a link.  But I think it could in turn become a rather vague instrument, detracting away from the purpose of conditions, maybe.  

Thanks

**Comment by YohannaLoucheur** [comment]
I think an approach as you describe, with a link to the web page explaining the general conditions, may work on our side. However, the feedback we got during the 2022 data collection was that we were required to publish documents with conditions specific to each activity.

**Comment by publishwhatyoufund** [comment]
@YohannaLoucheur , we agree with Steven that conditions are useful to publish at the activity level given the wide variety of IATI data use cases. 
All projects will have some kind of conditions attached such as performance milestones, fiduciary conditions or governance conditions. This can be published as a document or as data
